apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name:  cert-ssh

build:
#  tagPolicy:
#    dateTime:
#      format: "2006-01-02_15-04"

  artifacts:
    - image: gcr.io/dmeshgate/ssh-ca
      context: sshca/ssh-signerd
      custom:
        buildCommand: ./bin/ko-build.sh
        dependencies:
          paths:
            - "sshca/**"
            - "manifests/ssh-ca/**"

    - image: gcr.io/dmeshgate/sshd
      context: ssh/sshd
      custom:
        buildCommand: ../../bin/ko-build.sh
        dependencies:
          paths:
            - "ssh/**"
            - "manifests/sshd/**"

deploy:
  helm:
    releases:
      - name: ssh-ca
        namespace: ssh-ca
        createNamespace: true
        chartPath: ../../manifests/ssh-ca
        artifactOverrides:
          image: gcr.io/dmeshgate/ssh-ca
      - name: sshd
        namespace: sshd
        createNamespace: true
        chartPath: ../../manifests/sshd
        artifactOverrides:
          image: gcr.io/dmeshgate/sshd


portForward:
  - resourceType: deployment
    namespace: ssh-ca
    resourceName: ssh-ca
    port: 8080
    localPort: 14021

  - resourceType: deployment
    namespace: ssh-ca
    resourceName: ssh-ca
    port: 8081
    localPort: 14020

  - resourceType: deployment
    namespace: sshd
    resourceName: sshd
    port: 15022
    localPort: 14022
