apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: sshc
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sshc
  template:
    metadata:
      labels:
        app: sshc
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: default
      containers:
        - name: app
          image: {{ .Values.image }}
          workingDir: "/"
          ports:
          - containerPort: 8080
            name: http2
          - containerPort: 15022
            name: ssh
          args:
            - /usr/local/bin/sshc
          env:
            - name: SSHD
              value: s.webinf.duckdns.org:2222
            - name: SSH_AUTHORIZED_KEY
              value: "ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBRjGteKUhj757bQ8qaju5bvgWjoaZuGLvkq/Xnhr/LDW//qAk8O3v+RswbaCodSjKI6SDgFKl6samdUhP+kUwI= costin@costin15"
            - name: GOTRACEBACK
              value: "all"
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
          volumeMounts:
            - name: jwt-ssh-ca
              mountPath: /var/run/secrets/tokens/ssh
              readOnly: true
            # Only used for working in master mode (testing)
            - name: rootkey
              mountPath: /var/run/secrets/ssh-ca
              readOnly: true
            - name: mesh
              mountPath: /var/run/secrets/mesh
              readOnly: true

      volumes:
        - name: jwt-ssh-ca
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: ssh-ca
                  expirationSeconds: 43200
                  path: token

        - name: rootkey
          secret:
            secretName: ssh-ca
            optional: false
        - name: mesh
          secret:
            secretName: mesh
            optional: true
