apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: sshca
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sshca
  template:
    metadata:
      labels:
        app: sshca
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: default
      containers:
        - name: app
          #image: costinm/wps:latest
          #image: localhost:5000/wps:2020-05-24
          # For skaffold
          #image: ugate:latest
          image: {{ .Values.image }}
          imagePullPolicy: Always
          workingDir: "/"
          ports:
            - containerPort: 8080
              name: grpc
          env:
            - name: GOTRACEBACK
              value: "all"
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
          volumeMounts:
            # Default 'RO' config source
            - name: rootkey
              mountPath: /var/run/secrets/ssh-ca
              readOnly: true
      volumes:
        - name: rootkey
          secret:
            secretName: ssh-ca
            optional: false
