# Example of a standalone cloudrun app ( istio echo ) with an added sshm process.
# In this example the ssh process is not exposed over H2 tunnel - but uses a jump host.
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo-jumphost
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: ALPHA
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2

        # Attach to the VPC (no connector)
        run.googleapis.com/network-interfaces: '[{"network": "default", "subnetwork": "default"}]'

        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 1000
      timeoutSeconds: 900
      containers:
        - name: app
          image: ${IMG}
          # The start command is modified to start sshd first - which in turn starts the server.
          command: [ "/usr/local/bin/sshd", "/usr/local/bin/server" ]
          env:
            # Maintain a connection to this server.
            - name: SSHD
              value: costin15.webinf.duckdns.org:15022

            # Allow shell access for the users authenticated with the key.
            # Allow forwarding for users with keys signed by the CA or using JWTs
            - name: SSH_AUTHORIZED_KEYS
              value: |
                ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBRjGteKUhj757bQ8qaju5bvgWjoaZuGLvkq/Xnhr/LDW//qAk8O3v+RswbaCodSjKI6SDgFKl6samdUhP+kUwI= costin@costin15
                cert-authority ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDu9dWIA381ojxsUS8i0VJv0ED5Ac2zRFX1JijLjAO5HywPJ5a3CMM0NrXH5GqSoyDB/j92/Ta/f0QFAQZDhiFQ= ca.s.webinf.duckdns.org

            - name: DEPLOY
              value: "${DEPLOY}"

          resources:
            limits:
              cpu: '1'
              memory: 1G
