apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: ssh-mesh
build:
  local:
    push: true

  artifacts:
    # ghcr.io doesn't work in some places.
    # The github actions will create images there too.
    - image: docker.io/costinm/sshm
      context: ..
      custom:
        buildCommand: DOCKER_REPO=docker.io/costinm make all/sshm
        dependencies:
          paths:
            - cmd/**
            - sshd/*.go
            - manifests/sshm/**
    - image: docker.io/costinm/sshc
      #image: gcr.io/dmeshgate/sshc
      context: ..
      custom:
        buildCommand: DOCKER_REPO=docker.io/costinm make all/sshc
        dependencies:
          paths:
          - cmd/**
          - sshd/*.go
          - manifests/sshm/**
deploy:
  helm:
    releases:
      - name: sshd
        chartPath: sshm
        setValueTemplates:
          image: "{{.IMAGE_FULLY_QUALIFIED_docker_io_costinm_sshm}}"

        #artifactOverrides:
        #  image: gcr.io/dmeshgate/sshc:latest
        namespace: istio-system
        createNamespace: true

profiles:
  - name: home
    deploy:
      helm:
        releases:
          - name: sshd
            chartPath: sshm
            namespace: istio-system
            createNamespace: true
  - name: gcp1
    deploy:
      helm:
        releases:
          - name: sshd
            chartPath: sshm
            namespace: istio-system
            createNamespace: true

#portForward:
#- resourceType: deployment
#  resourceName: sshd
#  namespace: istio-system
#  port: 15022
#  localPort: 14022
#- resourceType: deployment
#  resourceName: ssh-ca
#  namespace: ssh-ca
#  port: 8081
#  localPort: 14020
#- resourceType: deployment
#  resourceName: sshd
#  namespace: sshd
#  port: 15022
#  localPort: 14022
