apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: ssh-mesh
build:
  artifacts:
  - image: gcr.io/dmeshgate/sshd
    context: .
    custom:
      buildCommand: make push
      dependencies:
        paths:
        - ssh/**
        - manifests/sshd/**
deploy:
  helm:
    releases:
    - name: sshd
      chartPath: ../../manifests/sshd
      artifactOverrides:
        image: gcr.io/dmeshgate/sshd
      namespace: sshd
      createNamespace: true
portForward:
- resourceType: deployment
  resourceName: ssh-ca
  namespace: ssh-ca
  port: 8080
  localPort: 14021
- resourceType: deployment
  resourceName: ssh-ca
  namespace: ssh-ca
  port: 8081
  localPort: 14020
- resourceType: deployment
  resourceName: sshd
  namespace: sshd
  port: 15022
  localPort: 14022
