{{/*apiVersion: cert-manager.io/v1*/}}
{{/*kind: Certificate*/}}
{{/*metadata:*/}}
{{/*  name: sshd-host*/}}
{{/*  namespace: istio-system*/}}
{{/*spec:*/}}
{{/*  issuerRef:*/}}
{{/*    kind: Issuer*/}}
{{/*    name: letsencrypt*/}}
{{/*  secretName: sshdhost*/}}
{{/*  commonName: {{ $.Values.domain }}*/}}
{{/*  dnsNames:*/}}
{{/*    - {{ $.Values.domain }}*/}}
