apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: default
      containers:
        - name: app
          image: {{ .Values.image }}
          workingDir: "/"
          ports:
          - containerPort: 8080
            name: http2
          - containerPort: 15022
            name: ssh
          #args:
          #  - /usr/local/bin/sshd
          env:
{{/*            - name: SSHD*/}}
{{/*              value: s.webinf.duckdns.org:2222*/}}
{{/*            - name: CFG_DIR*/}}
{{/*              value: "/var/run/sshd"*/}}
            - name: SSH_AUTHORIZED_KEY
              value: {{ .Values.sshOwner }}
            - name: GOTRACEBACK
              value: "all"
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
          volumeMounts:
            - name: sshm
              mountPath: /var/run/secrets/sshm
              readOnly: false
            - name: jwt-ssh-ca
              mountPath: /var/run/secrets/tokens/ssh
              readOnly: true
            # Only used for working in master mode (testing)
            - name: rootkey
              mountPath: /var/run/secrets/ssh-ca
              readOnly: true
            - name: mesh
              mountPath: /var/run/secrets/mesh
              readOnly: true

      volumes:
        - name: jwt-ssh-ca
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: ssh://ca
                  expirationSeconds: 43200
                  path: token

        - name: sshm
          configMap:
            name: sshd
            optional: true

        - name: rootkey
          secret:
            secretName: ssh-ca
            optional: true

        - name: mesh
          secret:
            secretName: mesh
            optional: true
