apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name:  sshd

build:
#  tagPolicy:
#    dateTime:
#      format: "2006-01-02_15-04"

  artifacts:
    - image: gcr.io/dmeshgate/sshd
      context: .
      custom:
        buildCommand: ../../bin/ko-build.sh
        dependencies:
          # Explicit - can also guess from Dockerfile
          paths:
            - "../**"
            - "../../manifests/sshd/**"
deploy:
  helm:
    releases:
      - name: sshd
        namespace: sshd
        createNamespace: true
        chartPath: ../../manifests/sshd
        artifactOverrides:
          image: gcr.io/dmeshgate/sshd

portForward:
  - resourceType: deployment
    namespace: sshd
    resourceName: sshd
    port: 15022
    localPort: 14022
