apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name:  ssh-ca

build:
  artifacts:
    - image: gcr.io/dmeshgate/ssh-ca
      context: .
      custom:
        buildCommand: ../../bin/ko-build.sh
        dependencies:
          paths:
            - "../**"
            - "../../manifests/ssh-ca/**"

deploy:
  helm:
    releases:
      - name: ssh-ca
        namespace: ssh-ca
        createNamespace: true
        chartPath: ../../manifests/ssh-ca
        artifactOverrides:
          image: gcr.io/dmeshgate/ssh-ca

portForward:
  - resourceType: deployment
    namespace: ssh-ca
    resourceName: ssh-ca
    port: 8080
    localPort: 14021

  - resourceType: deployment
    namespace: ssh-ca
    resourceName: ssh-ca
    port: 8081
    localPort: 14020
