name: Go
on: [push]

env:
  GO111MODULE: on

jobs:
  build-ko:
    name: Build with ko
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4
      - run: cd sshca && ko publish -B ./ssh-signerd
      - run: cd ssh && ko publish -B ./sshd

