name: goreleaser

on:
  push:
#    tags:
#      - '*'

permissions:
  contents: write

jobs:
  build-docker:
    name: Build-in-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3


      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: push
        run:
          make deps all DOCKER_REPO=ghcr.io/costinm

